### ISSUE TITLE
SPM: `spm build image` and `spm qemu 'StarLinux Image'`

### ISSUE THREAD

**Issue by AwlsomeAlex** [AwlsomeAlex/StarLinux#17]
### Image Package:
A cool concept that I could **POSSIBLY** do is create a temporary filesystem in a directory with ext4 format as a .img or .hdd and setup StarLinux as it would be the StarLinux Installation Guide for ArchLinux, but instead have SPM do it automatically removing the need for ArchLinux, then to be booted by either QEMU or your choice of Virtual Machine Manager. 
### QEMU Function:
Then SPM would load this image with QEMU, booting it possibly without the need of a bootloader (to remove space dependency and the need for Syslinux/GRUB).

**Comment by protonesso** [comment]
qemu-system-x86_64 - m 128 -kernel /path/to/kernel -initrd /path/to/rootfs
-append "[here's your commands for Linux kernel]"

**Comment by AwlsomeAlex** [comment]
@protonesso At this point would I need a disk image containing the filesystem? The InitramFS isn't created to handle StarLinux without a filesystem.

**Comment by AwlsomeAlex** [comment]
I found the command which will run everything to a certain point:
`qemu-system-x86_64 -m 128 -kernel kernel-$KERN_VER.xz -initrd initramfs-$KERN_VER.xz -hda hdd.img -append "root=/dev/sda"`
The `hdd.img` was generated by this command to the filesystem folder:
`mkisofs -o hdd.img filesystem/`

Now the problem is StarINIT tries to mount /dev/sda1 to /mnt/root, however QEMU will only mount hdd.img as /dev/sda. So I need to work on StarINIT so it can tell if it's in a QEMU Virtual Environment and if so, boot it a different way.

**Comment by protonesso** [comment]
make a raw image lol not with mkisofs. also you could make a "proc command line grabber"

**Comment by AwlsomeAlex** [comment]
What is this "proc command line grabber" you speak of?
And yeah a Raw Image might fix the problem completely. @protonesso

**Comment by AwlsomeAlex** [comment]
Well yeah that helped making it a raw image, as mkisofs screwed up the symlinks and caused a kernel panic after manual init, but QEMU still mounts the .img as /dev/sda which my init scripts are only made to boot off of /dev/sda1. It does work after manual init.
